### ISSUE TITLE
Setting config value (successfully?) prints error

### ISSUE THREAD

**Issue by dragorosson** [TileDB-Inc/TileDB-CSharp#197]
I'm following https://docs.tiledb.com/main/how-to/backends/gcs#gcs-setup
```
            var context = Context.GetDefault();
            context.Config().Set("vfs.gcs.project_id", "myproject");
```
This prints
```
[2022-12-24 10:07:19.328] [Process: 36276] [error] [1671897957280816100-Global] C API: Invalid TileDB error object
```
It doesn't seem like any error should be printed.

This is at https://github.com/TileDB-Inc/TileDB-CSharp/blob/b5d11da829f91bff5be6f02803a1d14d0869afb9/sources/TileDB.CSharp/Config.cs#L97
```
            if (status != (int)Status.TILEDB_OK)
            {
                var err_message = GetLastError(p_tiledb_error, status);
                Methods.tiledb_error_free(&p_tiledb_error);
                throw new ErrorException("Config.set, caught exception:" + err_message);
            }
            Methods.tiledb_error_free(&p_tiledb_error); // <-- HERE
```
I'm not very familiar with how the interop code works, but maybe this `free` isn't necessary because this code path didn't allocate anything?

**Comment by teo-tsirpanis** [comment]
Hello, maybe you are right. I added 74df698f1b3135e10ee128ccaa7fac631505bb46 on #191 which refactors the relevant error handling code.

**Comment by dragorosson** [comment]
@teo-tsirpanis Thanks!
