### ISSUE TITLE
Array.Exists or Array.TryOpen or similar?

### ISSUE THREAD

**Issue by dragorosson** [TileDB-Inc/TileDB-CSharp#222]
I don't always know if an array exists before trying to use it. Are there any methods to help with that?

My current approach doesn't seem like the "right" way to do it:

```
try
{
    Array.Create(context, array_uri, array_schema);
}
catch (Exception e)
{
    logger.Warn($"Array probably existed. Error: {e}");
}

// Do open, read/write, etc.
```

Since it's a one-time thing, it would be nice if the first time any read or write was going to happen, I could create the array if it didn't exist. I could see a number of different methods, any one of which would work for this:
- `bool array.Exists()`
- `bool array.TryCreate(...)`
- `bool array.TryOpen(...)`

Or perhaps this is considered an anti-pattern in TileDB? Any information would be helpful.

**Comment by teo-tsirpanis** [comment]
Hello, your snippet is fine. Once the new version is out you will be able to check for `context.GetObjectType(array_uri) == ObjectType.Array` to see if an array exists at the given path. It is more lightweight than opening the array.
