### ISSUE TITLE
Next release soon?

### ISSUE THREAD

**Issue by dragorosson** [TileDB-Inc/TileDB-CSharp#226]
A lot of good work has been done in the last month, including the addition of `FragmentInfo`, which I'm interested in using. Is a new release planned soon?

**Comment by teo-tsirpanis** [comment]
Hello, yes a new release is very close to completion. It will be released either today or next week.

**Comment by teo-tsirpanis** [comment]
[Version 5.3.0 has been released.](https://www.nuget.org/packages/TileDB.CSharp/5.3.0)
